version: 2.1

jobs:
  build_3-8-7:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nordvpn-old ./nordvpn-old
      - run: docker run --name nordvpn-old -d nordvpn-old
      - run: docker logs nordvpn-old && docker exec -d nordvpn-old echo ""
  build_3-8-8:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nordvpn-new ./nordvpn-new
      - run: docker run --name nordvpn-new -d nordvpn-new
      - run: docker logs nordvpn-new && docker exec -d nordvpn-new echo ""

workflows:
  build_and_test:
    jobs:
      - build_3-8-7
      - build_3-8-8