version: 2.1

jobs:
  build-old:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt-get update && apt-get install ca-certificates curl gnupg lsb-release -y
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: cd nordvpn-old
      - run: docker build
  build-new:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt-get update && apt-get install ca-certificates curl gnupg lsb-release -y
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: cd nordvpn-new
      - run: docker build

workflows:
  build_and_test:
    jobs:
      - build-old
      - build-new