version: 2.1

jobs:
  build_3-8-7:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nordvpn -f ./Dockerfile_3-8-7 .
      - run: docker run --name nordvpn -d nordvpn
      - run: docker logs nordvpn && docker exec -d nordvpn echo ""
  build_3-8-8:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nordvpn -f ./Dockerfile_3-8-8 .
      - run: docker run --name nordvpn -d nordvpn
      - run: docker logs nordvpn && docker exec -d nordvpn echo ""
  build_3-12-3:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nordvpn -f ./Dockerfile_3-12-3 .
      - run: docker run --name nordvpn -d nordvpn
      - run: docker logs nordvpn && docker exec -d nordvpn echo ""

workflows:
  build_and_test:
    jobs:
      - build_3-8-7
      - build_3-8-8
      - build_3-12-3