version: 2.1

jobs:
  build-old:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: cd nordvpn-old
      - run: docker build -t nordvpn-old ./nordvpn-old
      - run: docker run nordvpn-old
      - run: docker exec -d nordvpn-old echo "Working!"
  build-new:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: cd nordvpn-old
      - run: docker build -t nordvpn-new ./nordvpn-new
      - run: docker run -it nordvpn-new


workflows:
  build_and_test:
    jobs:
      - build-old
      - build-new